// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcEfOzluSozGorev.Data;

#nullable disable

namespace MvcEfOzluSozGorev.Data.Migrations
{
    [DbContext(typeof(UygulamaDbContext))]
    [Migration("20240116063302_Ilk")]
    partial class Ilk
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MvcEfOzluSozGorev.Data.OzluSoz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Soz")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yazar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OzluSozler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Soz = "Doğa bize hiçbir şey vermez, sadece ödünç alırız.",
                            Yazar = "John Ruskin"
                        },
                        new
                        {
                            Id = 2,
                            Soz = "Büyük ruhlar, eleştirilere sessiz kalabilirler.",
                            Yazar = "Franz Kafka"
                        },
                        new
                        {
                            Id = 3,
                            Soz = "Bilgi insanı özgür kılar.",
                            Yazar = "Kofi Annan"
                        },
                        new
                        {
                            Id = 4,
                            Soz = "Hayatınızdaki her şey bir şekilde düzenlenmiştir.",
                            Yazar = "Jim Rohn"
                        },
                        new
                        {
                            Id = 5,
                            Soz = "İyi bir kitap, iyi bir arkadaştır.",
                            Yazar = "Ernest Hemingway"
                        },
                        new
                        {
                            Id = 6,
                            Soz = "Sabırlı ol. Her şeyin olgunlaşması zaman alır.",
                            Yazar = "Tolstoy"
                        },
                        new
                        {
                            Id = 7,
                            Soz = "Hayatta sadece bir kez yaşarsınız, ancak doğru yaparsanız bir kez yeter.",
                            Yazar = "Mae West"
                        },
                        new
                        {
                            Id = 8,
                            Soz = "Zeka gücün anahtarıdır.",
                            Yazar = "Platon"
                        },
                        new
                        {
                            Id = 9,
                            Soz = "Hayatta hiçbir şey tesadüf değildir.",
                            Yazar = "Walt Disney"
                        },
                        new
                        {
                            Id = 10,
                            Soz = "Gözler kalbin penceresidir.",
                            Yazar = "İngiliz Atasözü"
                        },
                        new
                        {
                            Id = 11,
                            Soz = "Zorluklar sadece güçlü insanlara gelir.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 12,
                            Soz = "Zaman, sabrı olan her şeyi iyileştirir.",
                            Yazar = "Kofi Annan"
                        },
                        new
                        {
                            Id = 13,
                            Soz = "Küçük şeylerde mutluluğu bulabilen insanlar, gerçek zenginlerdir.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 14,
                            Soz = "Her gün bir adım attığınızda, bir gün dağları geçersiniz.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 15,
                            Soz = "Hayatınızdaki en değerli şey, sizin için en çok zaman harcadığınızdır.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 16,
                            Soz = "Hata yapmıyorsanız, muhtemelen yeterince denemiyorsunuzdur.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 17,
                            Soz = "Başarı, elde edilenlerden daha fazla başarısızlık anlamına gelmez.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 18,
                            Soz = "Yapabildiğiniz her şeyi yaparsanız, muhtemelen çok küçük düşünüyorsunuzdur.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 19,
                            Soz = "Başarılı bir insan, başarısızlığa uğramaktan korkmayandır.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 20,
                            Soz = "Hayatta sadece bir kere yaşarsınız, ama eğer doğru yaparsanız bir kere yeterlidir.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 21,
                            Soz = "Dünyayı değiştirmek istiyorsanız, kendinizden başlayın.",
                            Yazar = "Mahatma Gandhi"
                        },
                        new
                        {
                            Id = 22,
                            Soz = "Hayat, bisiklet sürmeye benzer. Dengeyi sürdüğünüz sürece düşmezsiniz.",
                            Yazar = "Albert Einstein"
                        },
                        new
                        {
                            Id = 23,
                            Soz = "Her insan bir gülüşle dünyayı değiştirebilir. Siz de bir insan mısınız?",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 24,
                            Soz = "Eğitim, geleceğin anahtarıdır.",
                            Yazar = "Malcolm X"
                        },
                        new
                        {
                            Id = 25,
                            Soz = "Bir şeyi istemek ve ona sahip olmak arasındaki fark, çalışmaktır.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 26,
                            Soz = "Dünyayı değiştirmek istiyorsanız, önce kendinizi değiştirin.",
                            Yazar = "Leo Tolstoy"
                        },
                        new
                        {
                            Id = 27,
                            Soz = "Hayal gücü, bilgiye kıyasla daha önemlidir.",
                            Yazar = "Albert Einstein"
                        },
                        new
                        {
                            Id = 28,
                            Soz = "Bir şeyi yapabiliyorsanız, yapmalısınız.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 29,
                            Soz = "Büyük şeyler küçük adımlarla başlar.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 30,
                            Soz = "Başarı için çalışmak, başarısız olmak için düşlemekten daha iyidir.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 31,
                            Soz = "Küçük bir gülümseme, dünyayı değiştirebilir.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 32,
                            Soz = "Hayatta başarılı olmak için, ilk önce başarılı olmuş insanların yaptıklarını taklit edin.",
                            Yazar = "Steve Jobs"
                        },
                        new
                        {
                            Id = 33,
                            Soz = "Hayatınızı kendiniz seçin, başkaları için yaşamayın.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 34,
                            Soz = "Daima bir öğrenci olun, asla bir usta olmayın.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 35,
                            Soz = "Büyük düşünmek, büyük başarılar getirir.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 36,
                            Soz = "Her başarı, bir deneme sonucudur.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 37,
                            Soz = "Bilgi güçtür.",
                            Yazar = "Francis Bacon"
                        },
                        new
                        {
                            Id = 38,
                            Soz = "Hayatta birçok şeyi değiştiremezsiniz, ancak tutumunuzu değiştirebilirsiniz.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 39,
                            Soz = "Geçmişi düşünmeyin, geleceği inşa edin.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 40,
                            Soz = "İyi bir lider olmak için önce iyi bir takım oyuncusu olmalısınız.",
                            Yazar = "John C. Maxwell"
                        },
                        new
                        {
                            Id = 41,
                            Soz = "Bir şeyi değiştiremezseniz, ona karşı değişin.",
                            Yazar = "Andy Warhol"
                        },
                        new
                        {
                            Id = 42,
                            Soz = "Mükemmel olmak, her zaman mükemmel bir performans sergilemek değildir.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 43,
                            Soz = "Başarı, bir dizi küçük çabadan doğar.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 44,
                            Soz = "Bir kapı kapanırsa, başka bir kapı açılır; ancak bazen o kadar uzun sürebilir ki, aradaki koridorde mahsur kalırsınız.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 45,
                            Soz = "Eğer herkes sizinle aynı fikirdeyse, muhtemelen yanlış bir şey yapıyorsunuzdur.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 46,
                            Soz = "Zor zamanlar, gerçek karakterinizi ortaya çıkarır.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 47,
                            Soz = "Kendine güven, başkalarının senin hakkında düşündüğünü umursamamaktır.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 48,
                            Soz = "Başkalarının başarısından korkmayın; öğrenin ve ilham alın.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 49,
                            Soz = "Çabucak unutulan, çabucak iyileşir.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 50,
                            Soz = "Sınırlarınızın ötesine geçin, orada büyüme gerçekleşir.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 51,
                            Soz = "Herkesin önünde gitmek, liderlik değildir. Gerçek lider, arkasında başkalarını bırakandır.",
                            Yazar = "John C. Maxwell"
                        },
                        new
                        {
                            Id = 52,
                            Soz = "Zor zamanlarda bile umutlu olun; çünkü o zamanlarda gerçek karakter ortaya çıkar.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 53,
                            Soz = "Değişim, yaşamın bir parçasıdır; gelişmeye direnmek, yaşamın bir kısmını kaçırmaktır.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 54,
                            Soz = "Eğitim, yaşamın anahtarıdır.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 55,
                            Soz = "Başarı, istediğin şeyi elde etmek; mutluluk, elde ettiğin şeyi sevmektir.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 56,
                            Soz = "Başkalarını değiştiremezsiniz, sadece kendinizi değiştirebilirsiniz.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 57,
                            Soz = "Daima bir öğrenci olun; hayatınız boyunca öğrenmekten vazgeçmeyin.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 58,
                            Soz = "Başarısızlık, başarıya giden bir basamaktır.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 59,
                            Soz = "Bir şeyi gerçekten istiyorsanız, nasıl yapılacağını bulacaksınız.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 60,
                            Soz = "Hayatınızı kendiniz seçin, başkaları için yaşamayın.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 61,
                            Soz = "Zamanın tadını çıkarın, çünkü geri alamazsınız.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 62,
                            Soz = "İyi bir karar, doğru zamanda alınan karardır.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 63,
                            Soz = "Herkes bir öğretmendir. Ne olması gerektiğinizi öğrenin ve öğretin.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 64,
                            Soz = "Gülümseme, insanların yaşamınız boyunca hatırlayacağı bir şeydir.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 65,
                            Soz = "Hayat, bir kez yaşanır, doğru yaşamak gerekir.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 66,
                            Soz = "Elinizdekiyle yetinin, ama hayalinizden vazgeçmeyin.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 67,
                            Soz = "Küçük şeylere önem verin, çünkü bir gün hatırlarsanız, aslında büyük şeylerdi.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 68,
                            Soz = "Zor zamanlar, gerçek gücünü ortaya çıkarır.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 69,
                            Soz = "Küçük adımlar, büyük başarılar getirir.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 70,
                            Soz = "Herkes hata yapar; önemli olan onlardan öğrenmektir.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 71,
                            Soz = "Başarı, yetenek ve çabanın birleşimidir.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 72,
                            Soz = "İyi bir lider, iyi bir dinleyicidir.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 73,
                            Soz = "Kendinizi olumlu şeylere odaklayın, olumlu şeyler sizi bulacaktır.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 74,
                            Soz = "Büyük başarılar, büyük riskler gerektirir.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 75,
                            Soz = "İyi bir kitap, bir arkadaştır.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 76,
                            Soz = "Küçük şeylerde mutluluk bulamıyorsanız, büyük şeylerde bulamazsınız.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 77,
                            Soz = "Hayatınızın amacını keşfedin ve ona odaklanın.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 78,
                            Soz = "Kendi hikayenizi yazın; başkaları sizin için yazmasın.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 79,
                            Soz = "İyi bir insan olmak, dünyada bir iz bırakmaktır.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 80,
                            Soz = "Bir şeyi yapamayacak kadar küçük olabilirsiniz, ancak onu yapabilecek kadar büyük de olabilirsiniz.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 81,
                            Soz = "Hayatta hiçbir şey için geç değildir.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 82,
                            Soz = "Küçük adımlar, büyük değişikliklere yol açabilir.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 83,
                            Soz = "Düşüncelerinizi gerçekleştirmek için harekete geçin.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 84,
                            Soz = "Başarı, bir dizi küçük çabadan doğar.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 85,
                            Soz = "Küçük şeylerde mutluluk bulamıyorsanız, büyük şeylerde bulamazsınız.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 86,
                            Soz = "En büyük zafer, kendini yenmektir.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 87,
                            Soz = "Mükemmel olma çabasında ol, mükemmel olmaya çalışma.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 88,
                            Soz = "Kendine güven, başkalarının senin hakkında ne düşündüğünü umursamamaktır.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 89,
                            Soz = "Zamanın tadını çıkarın, çünkü geri alamazsınız.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 90,
                            Soz = "Büyük düşünmek, büyük başarılar getirir.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 91,
                            Soz = "Hayatınızı yönlendirmenin en iyi yolu, onu kendiniz oluşturmaktır.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 92,
                            Soz = "Bir hedef belirleyin ve ardından ona ulaşmak için adım atın.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 93,
                            Soz = "Başarılı olmanın anahtarı, sabırlı ve azimli olmaktır.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 94,
                            Soz = "İyi bir fikir, başarılı bir eylemle buluştuğunda, harikalar yaratılır.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 95,
                            Soz = "Küçük şeylere önem verin, çünkü bazen en büyük mutluluklar orada gizlidir.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 96,
                            Soz = "Başarının arkasındaki sır, bir şeyleri başlatmaktır.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 97,
                            Soz = "Doğru zamanı bekleme, doğru zamanı yaratmaktır.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 98,
                            Soz = "Hayatınızdaki değerli anları hatırlayın, çünkü o anlar yaşamınızı değerli kılar.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 99,
                            Soz = "Başkalarına yardım etmek, gerçek mutluluğun anahtarıdır.",
                            Yazar = "Unknown"
                        },
                        new
                        {
                            Id = 100,
                            Soz = "Geleceği görmek için gözlerin yeter, sadece görmeyi bilmelisin.",
                            Yazar = "Albert Einstein"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
